version: 2
sources:
- name: dbt_vlakhmapurkar
  schema: dbt_vlakhmapurkar
  tables:
  - name: customers
    description: One record per customer.
  - name: orders
    description: One record per order. Includes cancelled and deleted orders.
models:
- name: stg_customers
  description: Staging model for customers
- name: customers_mart
  description: Mart model for customers
- name: stg_orders
  description: Staging model for orders
- name: orders_mart
  description: Mart model for orders
